#this is for claiming the volume from persistent volume
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: my-pv

  #here storageClassName should be similar to persistent volume storageclass to boud the status
  #to run this use cmd:kubectl apply -f PersistentVolumeClaim.yml
