#create your deployment.yml file
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-deployment
  namespace: ownserver
  labels:
    app: my-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-nginx

  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - name: own-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html
          name: my-storage
      volumes:
         -name: my-vol
          persistentVolumeClaim:
              claimName: my-pvc

      #here claim name should be your metadata name of persistentvolumeclaim 
     #here enter your own name to all of the things ensure that namespace is similar in which you want run your deployment
    #here defining volume path to store data when if the pods get delete 
